// <auto-generated />
using System;
using CitasMedicasAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitasMedicasAPI.Migrations
{
    [DbContext(typeof(DbdirectorioContext))]
    [Migration("20230918193503_HerenciaMigrate")]
    partial class HerenciaMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.Administradore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.CentrosMedicosClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdEspecialistaEspecialidad")
                        .HasColumnType("int");

                    b.Property<int?>("IdResponsable")
                        .HasColumnType("int");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonalCount")
                        .HasColumnType("int");

                    b.Property<string>("SitioWeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdEspecialistaEspecialidad");

                    b.HasIndex("IdResponsable");

                    b.HasIndex("IdRol");

                    b.ToTable("CentrosMedicosClinicas");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCita")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int?>("IdCmc")
                        .HasColumnType("int");

                    b.Property<int?>("IdEspecialista")
                        .HasColumnType("int");

                    b.Property<int?>("IdPaciente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCmc");

                    b.HasIndex("IdEspecialista");

                    b.HasIndex("IdPaciente");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.Especialidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.Especialista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EspecialidadeId")
                        .HasColumnType("int");

                    b.Property<int?>("IdEspecialistaEspecialidad")
                        .HasColumnType("int");

                    b.Property<int?>("IdResponsable")
                        .HasColumnType("int");

                    b.Property<string>("NumCedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolesUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadeId");

                    b.HasIndex("IdResponsable");

                    b.HasIndex("RolesUsuarioId");

                    b.ToTable("Especialistas");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.GrupEspecialidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdCMC")
                        .HasColumnType("int");

                    b.Property<int?>("IdEspecialidad")
                        .HasColumnType("int");

                    b.Property<int?>("IdEspecialidadNavigationId")
                        .HasColumnType("int");

                    b.Property<int?>("IdEspecialista")
                        .HasColumnType("int");

                    b.Property<int?>("IdEspecialistaNavigationId")
                        .HasColumnType("int");

                    b.Property<int?>("idCentrosMedicosClinicaNavigationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdEspecialidadNavigationId");

                    b.HasIndex("IdEspecialistaNavigationId");

                    b.HasIndex("idCentrosMedicosClinicaNavigationId");

                    b.ToTable("EspecialistasEspecialidades");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.Notificacione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCita")
                        .HasColumnType("int");

                    b.Property<bool?>("Leido")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdCita");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNac")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<int?>("IdRolNavigationId")
                        .HasColumnType("int");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdRolNavigationId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.RolesUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreRol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RolesUsuarios");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.CentrosMedicosClinica", b =>
                {
                    b.HasOne("CitasMedicasAPI.Data.CitasApiModels.GrupEspecialidade", "IdGrupEspecialidadeNavigation")
                        .WithMany("CentrosMedicosClinicas")
                        .HasForeignKey("IdEspecialistaEspecialidad");

                    b.HasOne("CitasMedicasAPI.Data.CitasApiModels.Administradore", "IdResponsableNavigation")
                        .WithMany("CentrosMedicosClinicas")
                        .HasForeignKey("IdResponsable");

                    b.HasOne("CitasMedicasAPI.Data.CitasApiModels.RolesUsuario", "IdRolNavigation")
                        .WithMany("CentrosMedicosClinicas")
                        .HasForeignKey("IdRol");

                    b.Navigation("IdGrupEspecialidadeNavigation");

                    b.Navigation("IdResponsableNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.Cita", b =>
                {
                    b.HasOne("CitasMedicasAPI.Data.CitasApiModels.CentrosMedicosClinica", "IdCmcNavigation")
                        .WithMany("Cita")
                        .HasForeignKey("IdCmc");

                    b.HasOne("CitasMedicasAPI.Data.CitasApiModels.Especialista", "IdEspecialistaNavigation")
                        .WithMany("Cita")
                        .HasForeignKey("IdEspecialista");

                    b.HasOne("CitasMedicasAPI.Data.CitasApiModels.Paciente", "IdPacienteNavigation")
                        .WithMany("Cita")
                        .HasForeignKey("IdPaciente");

                    b.Navigation("IdCmcNavigation");

                    b.Navigation("IdEspecialistaNavigation");

                    b.Navigation("IdPacienteNavigation");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.Especialista", b =>
                {
                    b.HasOne("CitasMedicasAPI.Data.CitasApiModels.Especialidade", null)
                        .WithMany("Especialista")
                        .HasForeignKey("EspecialidadeId");

                    b.HasOne("CitasMedicasAPI.Data.CitasApiModels.Administradore", "IdResponsableNavigation")
                        .WithMany("Especialista")
                        .HasForeignKey("IdResponsable");

                    b.HasOne("CitasMedicasAPI.Data.CitasApiModels.RolesUsuario", null)
                        .WithMany("Especialista")
                        .HasForeignKey("RolesUsuarioId");

                    b.Navigation("IdResponsableNavigation");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.GrupEspecialidade", b =>
                {
                    b.HasOne("CitasMedicasAPI.Data.CitasApiModels.Especialidade", "IdEspecialidadNavigation")
                        .WithMany("GrupEspecialidades")
                        .HasForeignKey("IdEspecialidadNavigationId");

                    b.HasOne("CitasMedicasAPI.Data.CitasApiModels.Especialista", "IdEspecialistaNavigation")
                        .WithMany("GrupEspecialidades")
                        .HasForeignKey("IdEspecialistaNavigationId");

                    b.HasOne("CitasMedicasAPI.Data.CitasApiModels.CentrosMedicosClinica", "idCentrosMedicosClinicaNavigation")
                        .WithMany()
                        .HasForeignKey("idCentrosMedicosClinicaNavigationId");

                    b.Navigation("IdEspecialidadNavigation");

                    b.Navigation("IdEspecialistaNavigation");

                    b.Navigation("idCentrosMedicosClinicaNavigation");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.Notificacione", b =>
                {
                    b.HasOne("CitasMedicasAPI.Data.CitasApiModels.Cita", "IdCitaNavigation")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdCita");

                    b.Navigation("IdCitaNavigation");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.Paciente", b =>
                {
                    b.HasOne("CitasMedicasAPI.Data.CitasApiModels.RolesUsuario", "IdRolNavigation")
                        .WithMany("Pacientes")
                        .HasForeignKey("IdRolNavigationId");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.Administradore", b =>
                {
                    b.Navigation("CentrosMedicosClinicas");

                    b.Navigation("Especialista");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.CentrosMedicosClinica", b =>
                {
                    b.Navigation("Cita");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.Cita", b =>
                {
                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.Especialidade", b =>
                {
                    b.Navigation("Especialista");

                    b.Navigation("GrupEspecialidades");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.Especialista", b =>
                {
                    b.Navigation("Cita");

                    b.Navigation("GrupEspecialidades");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.GrupEspecialidade", b =>
                {
                    b.Navigation("CentrosMedicosClinicas");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.Paciente", b =>
                {
                    b.Navigation("Cita");
                });

            modelBuilder.Entity("CitasMedicasAPI.Data.CitasApiModels.RolesUsuario", b =>
                {
                    b.Navigation("CentrosMedicosClinicas");

                    b.Navigation("Especialista");

                    b.Navigation("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
